### ISSUE TITLE
No contributors generated - (check shows contributors)

### ISSUE THREAD

**Issue by F1LT3R** [all-contributors/all-contributors-cli#110]
- `all-contributors-cli` version: 5.4.0
- `node` version: v10.10.0
- `npm` (or `yarn`) version: 6.4.1

What you did:

```shell
npx all-contributors init
# .all-contributors rc file now appears

npx all-contributors check

# Missing contributors in .all-contributorsrc:
#     F1LT3R, kflu, ChenYingChou, imyzf, alistair-hmh, anslzo, danhper, sushruth

npx all-contributors generate
```

What happened:

- No contributors added to `.all-contributorsrc`
- No contributors added to README.md

The README section looks like this:

```markdown
## Contributors

Thanks goes to these wonderful people ([emoji key](https://github.com/kentcdodds/all-contributors#emoji-key)):

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore -->
<!-- ALL-CONTRIBUTORS-LIST:END -->

This project follows the [all-contributors](https://github.com/kentcdodds/all-contributors) specification. Contributions of any kind welcome!
```

The `.all-contributorsrc` looks like this:

```json
{
  "projectName": "markserv",
  "projectOwner": "markserv",
  "repoType": "github",
  "repoHost": "https://github.com",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": true,
  "contributors": []
}
```

Problem description:

All-Contributors not working? 🤷‍♂️ 

Suggested solution:

Tell me how to fix it? 😂

**Comment by chinesedfan** [comment]
@F1LT3R I think you misunderstand usage of the command `generate`. It only generates content to README.md according to your config file, instead of fetching contributors automatically. What you really want is #49.

**Comment by F1LT3R** [comment]
Thanks, I will check that out.

**Comment by Berkmann18** [comment]
@F1LT3R The reason why you didn't see anyone on the list is that you didn't run `all-contributors add ...` for each contributor.
And `all-contributors check` only shows the contributors that aren't listed in `.all-contributorsrc`.
If you have any further questions/issues, feel free to re-open this or a new one.
