### ISSUE TITLE
New Category:  maintenance

### ISSUE THREAD

**Issue by GantMan** [all-contributors/all-contributors-cli#111]
Love the tool.  I was thinking it might be great if we could have a new category for those who simply come along and update dependencies.  They actually don't add code, but they help dependencies, and they maintain the "freshness" of a repo.

I've had a few come do that.

**Comment by kentcdodds** [comment]
Sure 👍

**Comment by GantMan** [comment]
:nut_and_bolt: Thoughts on this emoji for maintenance?

**Comment by GantMan** [comment]
I'll start the PR soon.  I have a talk to give next week.

Can this ticket be listed as a Hacktoberfest item? https://hacktoberfest.digitalocean.com/

**Comment by kentcdodds** [comment]
I don't think it has to be listed for you to get credit for the PR for hacktoberfest :)

**Comment by kentcdodds** [comment]
And that emoji is perfect

**Comment by Berkmann18** [comment]
Wouldn't :construction_worker: or :construction: be more appropriate for "maintenance"?

**Comment by GantMan** [comment]
I like the construction worker hat 👷 .   @Berkmann18 - It's been on my todo list but I have 2 major presentations this month.  If you can finish it in January, it's all yours.  If you still haven't done it by February, I'll come back and knock it out.

So feel free!

**Comment by jakebolam** [comment]
I like the construction worker but don't think we should use a gender specific emoji. See https://github.com/all-contributors/all-contributors/pull/49

**Comment by Berkmann18** [comment]
@jakebolam In this case using 🚧 or perhaps 🏗 would prevent that gender association?

**Comment by jakebolam** [comment]
Looks good to me. Happy with either.

**Comment by Berkmann18** [comment]
Okay, I'll use the former (since it's easier to understand).
