### ISSUE TITLE
a few questions about command

### ISSUE THREAD

**Issue by sli1989** [all-contributors/all-contributors-cli#112]
- `all-contributors-cli` version: 5.4.0
- `node` version: v8.12.0
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript

```

What you did:

```
npm run contributors:add jfmengels doc
```

What happened:

README.md and `.all-contributorsrc` are updated fine. but the bash command can't exit.
I must `ctrl+c` to exit to add other contributor.
Is it my command mistake?

and there is no difference after running  `npm run contributors:generate` . what's the meaning of the command.

Thanks for u help.

Reproduction repository:

Problem description:

Suggested solution:

**Comment by chinesedfan** [comment]
> README.md and .all-contributorsrc are updated fine. but the bash command can't exit.
I must ctrl+c to exit to add other contributor.

@sli1989 Sorry, I didn't reproduce the problem. Can you share the sample repository?

> and there is no difference after running npm run contributors:generate . what's the meaning of the command.

In fact, `npm run contributors:add jfmengels doc` modifies `.all-contributorsrc`and generates changes to files. If modified `.all-contributorsrc` manually, you can use `npm run contributors:generate`.

**Comment by sli1989** [comment]
oh, thanks. The live demo is here: https://github.com/sli1989/hexo-theme-next/tree/contributors.

**Comment by chinesedfan** [comment]
@sli1989 Still didn't find anything wrong. Can you try `npm run contributors:add jfmengels doc --verbose` and check where it hangs at?

**Comment by sli1989** [comment]
just stay like this, no exit out.

```
Administrator@DESKTOP-ALEX MINGW64 /f/alex/hexo/themes/next (contributors)
$ npm run contributors:add jfmengels doc --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'contributors:add',
npm verb cli   'jfmengels',
npm verb cli   'doc',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v8.12.0
npm verb run-script [ 'precontributors:add',
npm verb run-script   'contributors:add',
npm verb run-script   'postcontributors:add' ]
npm info lifecycle hexo-theme-next@6.4.2~precontributors:add: hexo-theme-next@6.4.2
npm info lifecycle hexo-theme-next@6.4.2~contributors:add: hexo-theme-next@6.4.2

> hexo-theme-next@6.4.2 contributors:add F:\alex\hexo\themes\next
> all-contributors add "jfmengels" "doc"



```

**Comment by chinesedfan** [comment]
Hmm, Windows OS. Did you install `git` in your cmd? How about deleting `commit: true` in `.all-contributorsrc`?

**Comment by sli1989** [comment]
> Did you install git in your cmd?

I don't know this meaning. I use the Git Bash.

> How about deleting commit: true in .all-contributorsrc?

It makes no difference.

**Comment by chinesedfan** [comment]
I'm afraid I can't help you more. Maybe you can debug from `node_modules/all-contributors-cli/dist/cli.js` or wait for others' help.

**Comment by sli1989** [comment]
thanks anyway. 🍺

**Comment by Berkmann18** [comment]
@sli1989 Friendly ping.

**Comment by Berkmann18** [comment]
I'm going to close this issue as it seems that it may have been resolved.
@sli1989 If your questions are still unanswered then please let me know and I'll re-open it.
