### ISSUE TITLE
Using a custom badge template breaks badge replacement

### ISSUE THREAD

**Issue by simbas** [all-contributors/all-contributors-cli#120]
- `all-contributors-cli` version: 5.4.1
- `node` version: v11.4.0
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript
{
  "projectName": "test",
  "projectOwner": "me",
  "repoType": "github",
  "repoHost": "https://github.com",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "badgeTemplate": "![Contributors](https://img.shields.io/badge/contributors-<%= contributors.length %>-orange.svg)",
  "contributors": []
}
```

What you did:
```shell
npm init -y
npm i --save-dev all-contributors-cli
touch README.md
npx all-contributors init # with default params

# then adds a custom badge template
awk '/contributors/{print "  \"badgeTemplate\": \"![Contributors](https://img.shields.io/badge/contributors-<%= contributors.length %>-orange.svg)\","}1' .all-contributorsrc | tee .all-contributorsrc

npx all-contributors add jfmengels code
cat README.md # the badge has been updated

npx all-contributors add simbas code
cat README.md # the badge has not been updated
```

What happened:
The badge regex `/\[!\[All Contributors\]\([a-zA-Z0-9\-./_:?=]+\)\]\(#\w+\)/;` is not working with custom badge template.

Suggested solution:
- badge regex as a property of the .all-contributorsrc file
- use the badge template to find the badge (generate the regex from the template?)

**Comment by jakebolam** [comment]
I'd feel happy with either solution. @simbas want to do what you think is best and put up a PR on the project?

**Comment by simbas** [comment]
Hello @jakebolam, thank you for your reply.

Maybe there is a third solution which is using tags to find the badge:
```
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
<!-- ALL-CONTRIBUTORS-BADGE:END -->
```
What do you think about that?

**Comment by jakebolam** [comment]
@simbas sounds like a great idea :)

**Comment by jakebolam** [comment]
Similar issue: https://github.com/codingblocks/qit.cloud/pull/307
