### ISSUE TITLE
Script doesn't work with and without nps and exits with 1

### ISSUE THREAD

**Issue by erdahuja** [all-contributors/all-contributors-cli#146]
https://www.dropbox.com/s/btvqq2cl0ediy21/Screenshot%202018-06-16%2003.28.21.png?dl=0

**Comment by Berkmann18** [comment]
@erdahuja Thanks for reporting the issue.
Both dropbox link resolve into a 404 error. Have you used the _shared links_?

**Comment by Berkmann18** [comment]
@erdahuja Friendly ping.

**Comment by erdahuja** [comment]
@Berkmann18 Hi, sorry for not following the thread. i always double check the links and they work because they are auto generated. Not sure why they aren't working now. I'll retry and get back to you

**Comment by Berkmann18** [comment]
Okay.

**Comment by erdahuja** [comment]
It works now, we can close this issue. Thanks for caring about it :)

**Comment by erdahuja** [comment]
> It works now, we can close this issue. Thanks for caring about it :)

**Comment by Berkmann18** [comment]
Superb 😄, I'm glad it's resolved.
