### ISSUE TITLE
all-contributors generate 

### ISSUE THREAD

**Issue by githubsaturn** [all-contributors/all-contributors-cli#152]
- `all-contributors-cli` version: 5.10.2
- `node` version: v10.15.0
- `npm` (or `yarn`) version: 6.4.1

Isn't `all-contributors generate` supposed to generate the list of contributors automatically?

```bash
#!/bin/sh

git clone git@github.com:caprover/caprover.git
cd caprover
npm install --save-dev all-contributors-cli
npx all-contributors init
npx all-contributors check
npx all-contributors generate
cat README.md
```

What you did:

Ran the script above and I was expecting that contributors are automatically added to README.md after running those commands. However, the `npx all-contributors generate` just exits and nothing gets added to README.md

`npx all-contributors check` works fine. It prints all missing contributors on screen, however, `npx all-contributors generate` does not do anything.

This issue is similar to https://github.com/all-contributors/all-contributors-cli/issues/93.
But it's not the same, because the additional `...ALL-CONTRIBUTORS-LIST:START...` stuff are added to README.md

**Comment by jakebolam** [comment]
@githubsaturn (sorry for the accidental close, on my phone)

Generate will generate the list of contributors based on the `.all-contributorsrc` file. (PRs welcome to make the docs clearer on this)

`init` is intended for new projects, but does not automatically fetch the list of contributors (yet).

If your interested in contributing to an auto-generated/fetch feature there is some discussion in #117.

**Comment by jakebolam** [comment]
Just curious (to help us strive to continue to build better tooling). Did you by chance [come across the new bot?](HTTPS://GitHub.com/all-contributors/all-contributors-bot) Any reason for choosing the CLI over the bot?

**Comment by githubsaturn** [comment]
> Just curious (to help us strive to continue to build better tooling). Did you by chance come across the new bot? Any reason for choosing the CLI over the bot?

Exactly because of issues like this one. I generally don't trust a bot to come and make changes for me unless it's a very well known bot. As a rule of thumb, I'd like to inspect what is being done closely.

**Comment by githubsaturn** [comment]
PS: I close this issue. As it's not a bug. It's working as intended.

I was under the impression that the premise of this project is to autogenerate the contributor list for you - similar to Open Collective. See this one for example: https://github.com/parcel-bundler/parcel#contributors

**Comment by jakebolam** [comment]
> Exactly because of issues like this one. I generally don't trust a bot to come and make changes for me unless it's a very well known bot. As a rule of thumb, I'd like to inspect what is being done closely.

Fair enough. The entire [source code for the bot](https://github.com/all-contributors/all-contributors-bot/tree/master/src) (as well as infrastructure etc) is all completely open source.

**Comment by jakebolam** [comment]
> I was under the impression that the premise of this project is to autogenerate the contributor list for you - similar to Open Collective. See this one for example: https://github.com/parcel-bundler/parcel#contributors

Oh yeah, that makes sense. We've held off for a while on this feature, as all-contributors is intended to recognise all contributors ✨ not just those who code. We understand there is a barrier of entry on existing projects, and will hopefully have something in the future to help automate this.
