### ISSUE TITLE
Switch table generation to HTML

### ISSUE THREAD

**Issue by jakebolam** [all-contributors/all-contributors-cli#154]
Been looking to improve the look of the table. Indirectly as part of other tickets (https://github.com/all-contributors/all-contributors-bot/issues/101)

Is there any strong reason for staying with markdown? Or could we switch the table generation over to HTML (in a breaking_change release) ?

## Reasons for switching to HTML:
- Improving the table layout on all-screens/devices
- Additional customization of the table (e.g. colspan, width control etc)

## Reasons for sticking with Markdown
- Possible projects using website generators from markdown that have the table?

**Comment by kentcdodds** [comment]
Happy to see it improved. Either way works.

**Comment by Berkmann18** [comment]
I'll give this a go and see what I get.
