### ISSUE TITLE
On adding non existent github user name, error shown is not descriptive.

### ISSUE THREAD

**Issue by erdahuja** [all-contributors/all-contributors-cli#170]
- `all-contributors-cli` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

```javascript

```

What you did:
added non github username  contributor.

What happened:

![image](https://user-images.githubusercontent.com/15168716/53261692-b05b2d00-36fa-11e9-9bfa-d942d1cc638f.png)

Reproduction repository:
Simply run cli tool "yarn run all-contributors" and answer question 1 with wrong username.

Problem description:

Suggested solution:

A better error message

**Comment by Berkmann18** [comment]
Thanks for reporting that, what error message would you expect in the above scenario?
Would you mind opening a PR?

**Comment by erdahuja** [comment]
Ok i can, what's a good starting point for adding these.

**Comment by erdahuja** [comment]
I checked the code throws a common error for not found cases. This is very confusing for end users and non informative. let me try adding some value here.

**Comment by erdahuja** [comment]
@Berkmann18 I have fixed it, how to add a PR? i dont have permissions.

My email id - er.d.ahuja@gmail.com
github.com/erdahuja

**Comment by sinchang** [comment]
@erdahuja you can see this tutorial http://makeapullrequest.com/

**Comment by jakebolam** [comment]
@erdahuja how's it going? Is there anything we can help with

**Comment by erdahuja** [comment]
@jakebolam Please merge my [PR](https://github.com/all-contributors/all-contributors-cli/pull/171) it's completed with tests, also approved.
