### ISSUE TITLE
Pretty-print/Format the generated HTML table

### ISSUE THREAD

**Issue by nschonni** [all-contributors/all-contributors-cli#189]
- `all-contributors-cli` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

What you did:
Enjoyed the bot adding/creating the HTML table

What happened:
The diffs for the HTML table are difficult to parse since they are all on one line

Reproduction repository:
https://github.com/entropic-dev/entropic/pull/179/files

Problem description:
The HTML table currently is  emmitted as a single line, that makes a diff hard to read, compared to the json file

Suggested solution:
"Pretty Print" the table code so the elements are on separate lines (and possibly indented).
I would also assume this is better git-blob wise since it is a smaller amount of data if 2-3 short lines change vs 1 very long line (this is a guess).

**Comment by Berkmann18** [comment]
I like your suggestion, would you be up for submitting a PR?
