### ISSUE TITLE
Pretty small detail: badge doesn't link to the Contributors section

### ISSUE THREAD

**Issue by rachelcarmena** [all-contributors/all-contributors-cli#195]
## Data

- `all-contributors-cli` version: **v6.7.0**
- `node` version: _it doesn't depend on this version_
- `npm` (or `yarn`) version: _it doesn't depend on this version_

## Problem description:

The problem occurs in `README.md`.

The badge links to `#contributors` :

```
[ ... ](#contributors)
```

while the Contributors section has the link `#contributors-` instead of `#contributors` because of the final sparkles in the title ✨

## Suggested solution:

Firstly, I changed badge link to `(#contributors-)`. It didn't work because the badge wasn't updated when adding new collaborators. Reason: the source code is coupled with having only word characters (`\w`) in the link:

* `src/generate/index.js`
```javascript
const badgeRegex = /\[!\[All Contributors\]\([a-zA-Z0-9\-./_:?=]+\)\]\(#\w+\)/
```

My local solution was to remove the sparkles at the end of Contributors title.

If we want to keep sparkles then source code might be changed to consider `-` in the regex as well as changing the initial content:

* `src/init/init-content.js`
```javascript
const badgeContent =
'[![All Contributors](https://img.shields.io/badge/all_contributors-0-orange.svg?style=flat-square)](#contributors)'
```

**Comment by Berkmann18** [comment]
Thanks for pointing that out.
That sparkle thing was introduced in #136 (`v6.6.0`) and there was no discussion in removing that so I think to have the code being updated to accommodate that would be the next step.

Would you mind opening a PR for this?

**Comment by rachelcarmena** [comment]
Of course!! Thanks for the opportunity to help with a tool that helps me :dancer: :dancer: :dancer: 

Awesome!! I made a PR as soon as possible :rocket:

**Comment by Berkmann18** [comment]
Superb, I'm looking forward to your PR.
I'm glad to hear that this tool helps you 😀.

**Comment by rachelcarmena** [comment]
Done, @Berkmann18 ! :rocket: https://github.com/all-contributors/all-contributors-cli/pull/197
