### ISSUE TITLE
Hyphen in user name problem

### ISSUE THREAD

**Issue by marekrozmus** [all-contributors/all-contributors-cli#225]
@all-contributors please add aaa-bbb for bug, ideas

Will add user `aaa` not a `aaa-bbb` user.

**Comment by marekrozmus** [comment]
@Berkmann18 

bot is listening 😉 Anyway in the [documentation](https://allcontributors.org/docs/en/bot/usage) this information about the `@` prefix is missing. It is only visible on screenshot that is why I got confused.

**Comment by Berkmann18** [comment]
Hmm, good catch. Feel free to submit a PR for this if you can.
If not, I'll do it but I'm very busy at the moment.

**Comment by baikho** [comment]
I believe we can also close this one now with https://github.com/all-contributors/all-contributors-bot/pull/307, given that this actually relates to the bot repo?

**Comment by Berkmann18** [comment]
@baikho Yup, correct.
