### ISSUE TITLE
[QUESTION] Different Languages?

### ISSUE THREAD

**Issue by fforres** [all-contributors/all-contributors-cli#25]
Is it considered to have multiple languages on this tool? 
(Maybe it's already implemented or planned)
If not, I'd love to add a PR 😄

**Comment by fforres** [comment]
Specifically for this piece of text: 
`This project follows the [all-contributors](https://github.com/kentcdodds/all-contributors) specification. Contributions of any kind welcome!` :)

**Comment by kentcdodds** [comment]
I think that'd be great. We definitely want to be as inclusive as we can. It's up to @jfmengels, but I'd personally accept a PR if it were my decision.

**Comment by jfmengels** [comment]
Sure, why not :)

I'm thinking of a `language` setting in the rc file, with English as the default.
If you're up for it @fforres, I'd love a PR :)

**Comment by fforres** [comment]
Awesome 👍 
Just created the PR: https://github.com/jfmengels/all-contributors-cli/pull/31

**Comment by Berkmann18** [comment]
@fforres Are you still planning on working on the PR?

**Comment by Berkmann18** [comment]
Since we have Crowdin and this has been inactive for quite some time, I'll close it.
Feel free to re-open (if need be).
