### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ilai-deutel** [all-contributors/all-contributors-cli#254]
Hi,

Could you please add a `LICENSE` file to the repository? I would like to package `all-contributors-cli` for the Arch User Repository and a LICENSE file is required (since the MIT license must include a project-specific copyright line).

Thanks!

**Comment by Berkmann18** [comment]
Hi @ilai-deutel, thanks for pointing out that it was missing, I've added one on #255.
