### ISSUE TITLE
Contributor profile url need to be validated

### ISSUE THREAD

**Issue by k3nsei** [all-contributors/all-contributors-cli#267]
- `all-contributors-cli` version: 6.15.0
- `node` version: 14.2.0
- `npm` (or `yarn`) version: 1.22.4

What you did:

```yarn run all-contributors add Silvest89```
```yarn run all-contributors generate```

What happened:

Silvest89 has some string instead of url. So after generation of contributors template. Code was invalid html.

Suggested solution:

Please validate if url in github profile if it is valid url. If it isn't please use url to github profile.

**Comment by Berkmann18** [comment]
Hmm, that definitely shouldn't happen, feel free to submit a PR for this.

**Comment by k3nsei** [comment]
@Berkmann18 sure will do
