### ISSUE TITLE
markdownlint-disable/enable is the wrong pattern; use disable/restore instead

### ISSUE THREAD

**Issue by DavidAnson** [all-contributors/all-contributors-cli#276]
- `all-contributors-cli` version: Latest
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

Relevant code or config

- <https://github.com/all-contributors/all-contributors-cli/blob/72de75abc51ef73e2782a70de7a2be26342bf22f/src/init/init-content.js#L15-L16>
- <https://github.com/all-contributors/all-contributors-cli/blob/d26cd47c817ffbbcdc7362b50c0d066fc2820975/src/generate/index.js#L30-L32>

What you did:

Investigated an issue reported by @bnb where `markdownlint` rules were being ignored in a specific file that was generated by this project.

What happened:

The pattern produced by this project of `<!-- markdownlint-disable -->` then `<!-- markdownlint-enable -->` in the two files referenced above has the effect of (re-)enabling *all* `markdownlint` rules. In cases where the relevant project/file/user has disabled some (ex: `line-length`), they are undesirably enabled for the remainder of the file. Instead, use `<!-- markdownlint-restore -->` to restore the previously-enabled rules.

There's a discussion and example here: <https://github.com/DavidAnson/markdownlint#configuration>

Reproduction repository:

Any repository that uses the pattern above.

Problem description:

See above.

Suggested solution:

See above.

**Comment by Berkmann18** [comment]
I'm not quite sure where the issue is, this disable/enable comment section is there to prevent a previously raised issue where MarkdownLint would complain about the table not respecting rules while _still_ allowing it to do its job as far as the rest of the file (e.g. `README.md`) is concerned.

**Comment by bnb** [comment]
@Berkmann18 the problem is that `enable` turns on all rules ignoring the users' initial config. In my case, I had a rule I was ignoring that was triggered _after_ the all-contributors block, and because `enable` is used rather than `restore`, my config was ignored and the rules were reset to defaults which was throwing errors rather than restoring my rules.

**Comment by Berkmann18** [comment]
@bnb That makes sense. A PR would be welcome for this.

**Comment by DavidAnson** [comment]
Here’s a visual demonstration:

[What it does](https://dlaa.me/markdownlint/#%25m%23%20all-contributors-cli%0A%0AThe%20line-length%20rule%20has%20been%20disabled.%20The%20line-length%20rule%20has%20been%20disabled.%20The%20line-length%20rule%20has%20been%20disabled.%0A%0A%3C!--%20markdownlint-disable%20--%3E%0Aall-contributors-cli%20stuff%0A%3C!--%20markdownlint-enable%20--%3E%0A%0AYou%20reset%20the%20rule%20and%20this%20is%20now%20an%20error.%20You%20reset%20the%20rule%20and%20this%20is%20now%20an%20error.%0A)

[What it should do](https://dlaa.me/markdownlint/#%25m%23%20all-contributors-cli%0A%0AThe%20line-length%20rule%20has%20been%20disabled.%20The%20line-length%20rule%20has%20been%20disabled.%20The%20line-length%20rule%20has%20been%20disabled.%0A%0A%3C!--%20markdownlint-disable%20--%3E%0Aall-contributors-cli%20stuff%0A%3C!--%20markdownlint-restore%20--%3E%0A%0AThis%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%20This%20is%20okay.%0A)

**Comment by DavidAnson** [comment]
@bnb I probably won't get to this anytime soon. If you want to send the PR, please go ahead.￼ The change is trivial, but I don't know how easy/hard it will be to add tests, etc.￼.

**Comment by DavidAnson** [comment]
I decided to YOLO a PR. All checks pass. Here you go: https://github.com/all-contributors/all-contributors-cli/pull/278
