### ISSUE TITLE
Wrong errors message when API rate limit exceeded

### ISSUE THREAD

**Issue by shairez** [all-contributors/all-contributors-cli#284]
- `all-contributors-cli` version: 6.17.2
- `node` version: 12.14.0
- `npm` (or `yarn`) version: yarn 1.21.1

Relevant code or config

```javascript
// github.js

if (!profile && body.message) {
   throw new Error(`Login not found when adding a contributor for username - ${username}.`);
}
```

**What you did:**

Tried to add a contributor via the CLI

**What happened:**

![image](https://user-images.githubusercontent.com/1430726/93320725-16962c00-f81a-11ea-8cd3-92d3cd8701a5.png)

**Problem description:**
First of all - the error "login not found" doesn't really tell that it means that the "user not found on github".

But that's not the problem here, the username does exist.

After putting some console.logs in `repo/github.js` I saw that the `body.message` complains about `API rate limit exceeded for...` 

**Suggested solution:**
It's better to show the real issue as an error, and to search for "API rate limit exceeded for" and show that message instead of the "login not found", which BTW, should be changed to "username not found on github" or something.

Let me know what you think and I'll create a PR for it

**Comment by Berkmann18** [comment]
Your solution looks good to me.

**Comment by shairez** [comment]
Cool, I created #286 to fix this.
Feel free to modify the error message / test if you feel it needs improvement.
