### ISSUE TITLE
Namespace API tokens to eliminate name collision 

### ISSUE THREAD

**Issue by SirWindfield** [all-contributors/all-contributors-cli#294]
Hey!

I have an old CLI tool installed that also assumes that I have an environment variable named `PRIVATE_TOKEN` set. It would be awesome if this CLI would namespace the variable, for example `ALL_CONTRIBUTORS_PRIVATE_TOKEN` (or even with Gitlab and GitHub specific variants but that would be out of scope for now). This would eliminate namespace conflicts. 

This can be implemented in a backwards-compatible manner. It would first check for the namespaced variant and fallback to the current name.

The namespacing is done in popular CLIs such as `npm`, `diesel` and `yarn` as well, just to name a few.

**Comment by SirWindfield** [comment]
I'd be open to create a PR if this would get merged!

**Comment by Berkmann18** [comment]
Sounds good to me, a PR would be welcome.

**Comment by eliane345** [comment]
Desculpe o transtorno!
