### ISSUE TITLE
Generate from GitHub?

### ISSUE THREAD

**Issue by DirtyF** [all-contributors/all-contributors-cli#49]
Hi,

First of all, thanks for this.

I would like to know if there is a way to generate all existing contributors list from a GitHub repo at once? Nothing happens when I try to `generate` with an empty contributors file after init. 
Do you have to add each contributor with `add`?

**Comment by kentcdodds** [comment]
Hi @DirtyF!

Thanks for the issue. Unfortunately there's not anything like that. If you'd like to build it that would be cool! Could probably be part of the `init` script as an option or something. Feel free to [make a pull request](http://makeapullrequest.com/).

What I think would be an even more valuable use of time would be to make the CLI unnecessary by [creating a bot](https://github.com/kentcdodds/all-contributors/issues/58)! If you'd like to work on that, I would be so grateful :)

Thanks!

**Comment by GantMan** [comment]
Ok, I'm strongly interested in adding this feature.  If no one else has started it, I wouldn't mind giving it a go.

Would it be ok if I made a separate CLI that USES this cli to add each person?  We could then link to it in the readme.  That would be the fastest way for me to contribute.

**Comment by kentcdodds** [comment]
Thanks for your interest @GantMan!

I'm definitely interested in making this fast for you to contribute, but I'm more interested in the "right" solution. I think the right solution would be to have this functionality built into this tool. So if you could please contribute to this project that would be great. I'm sure @machour would be happy to help answer any questions you have and I'll try to help where I can.

**Comment by GantMan** [comment]
Sounds good.   I see `var var var function` and my gut reaction is O NOOOOOO!!!!!!!
It's a little harder, but hard tasks make strong minds.  I'll give it a go!  No promises on timelines.

**Comment by Berkmann18** [comment]
The issue #117 encompasses this and @mrchief proposed to help on that.
