### ISSUE TITLE
Allow removing contribution types when editing an existing user

### ISSUE THREAD

**Issue by machour** [all-contributors/all-contributors-cli#61]
There is currently no way to remove a contribution type using the cli, as noticed in #60

**Comment by tyler-reitz** [comment]
I'd like to take a stab at this. 

Should this live alongside: https://github.com/jfmengels/all-contributors-cli/blob/1562a379db19ba881c8d9f27b520f27262ce7c68/src/contributors/add.js#L28 or be broken off on it's own?

Also, I think this prompt https://github.com/jfmengels/all-contributors-cli/blob/1562a379db19ba881c8d9f27b520f27262ce7c68/src/cli.js#L133 will have to be updated

**Comment by machour** [comment]
Hi @tyler-reitz and thank you for hopping in!

I think that the problems is in this function: https://github.com/jfmengels/all-contributors-cli/blob/1562a379db19ba881c8d9f27b520f27262ce7c68/src/contributors/add.js#L7-L16

Imagine we had ["doc", "bug"] as `existing` and we unchecked "bug", so `types` is ["doc"]
currently, by using concat(), we end up again with ["doc", "bug"]. The code needs to be updated to dismiss existing contributions that have been removed from `types` (or maybe simply use types?  🤔 )

As for the prompt, less keep it simple: "Add new contributor or edit contribution type"

**Comment by tyler-reitz** [comment]
Where's the `options.url` coming from ? at https://github.com/jfmengels/all-contributors-cli/blob/1562a379db19ba881c8d9f27b520f27262ce7c68/src/contributors/add.js#L8  I don't see anywhere to add it via either the prompt or by passing argument directly via the cli.

**Comment by Berkmann18** [comment]
@tyler-reitz Friendly ping.

**Comment by baikho** [comment]
I was about to look into this but this has already been implemented by @jakebolam in it seems.

I can remove existing contributor's contributions both via interactive mode and the `all-contributors add` command. See relevant test case `should update an existing contributor's contributions if an existing type is removed` that accounts for this in https://github.com/all-contributors/all-contributors-cli/blob/master/src/contributors/__tests__/add.js

**Comment by Berkmann18** [comment]
@baikho Good point, it's bizarre that the PR wasn't linked.
