### ISSUE TITLE
Unknown error on adding contributors via expanded syntax

### ISSUE THREAD

**Issue by blackxored** [all-contributors/all-contributors-cli#70]
For some reason, i'm getting exit code 1 (without an error, since I've added debugging and it properly returns `undefined` for `error` in the handler) when running:
```shell
$ add-contributors add blackxored code,doc,infra,test
$ echo $?
1
```
On README.md
```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
| [<img src="https://avatars3.githubusercontent.com/u/133308?v=4" width="100px;"/><br /><sub><b>Adrian Perez</b></sub>](https://adrianperez.codes)<br />[💻](https://github.com/blackxored/testapp/commits?author=blackxored "Code") [🚇](#infra-blackxored "Infrastructure (Hosting, Build-Tools, etc)") [⚠️](https://github.com/black xored/testapp/commits?author=blackxored "Tests") [📖](https://github.com/blackxored/testapp/commits?author=blackxored "Documentation") |
| :---: |
<!-- ALL-CONTRIBUTORS-LIST:END -->
```

It successfully generates, adds to the contributors in .allcontributorsrc, and everything seems to work, but somehow I'm getting that exit code.

**Comment by machour** [comment]
@blackxored just tested it on my side and the exit code for me is 0
```
🍺  ~/all-contributors-cli-prod (master)$ ./cli.js add blackxored code,doc,infra,test
🍺  ~/all-contributors-cli-prod (master)*$ echo $?
0
```

Can you make sure you are using the latest version? (4.8.1 at the time of writing)

**Comment by blackxored** [comment]
Yes, on the latest version. 
Pasting .all-contributorsrc:
```json
{
  "projectName": "testapp",
  "projectOwner": "blackxored",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": true,
  "contributors": [
    {
      "login": "blackxored",
      "name": "Adrian Perez",
      "avatar_url": "https://avatars3.githubusercontent.com/u/133308?v=4",
      "profile": "https://adrianperez.codes",
      "contributions": [
        "code",
        "infra",
        "test",
        "doc"
      ]
    }
  ]
}
```

**Comment by machour** [comment]
Could you try setting commit to `false`? Let's see if it's a commit issue

**Comment by blackxored** [comment]
Yes, `commit` seems to be the issue, unsure why.

**Comment by kentcdodds** [comment]
We're thinking of removing that feature. I never liked or used it. It seems to be fairly buggy in general.

**Comment by chinesedfan** [comment]
@blackxored I guess the commit fails silently. Maybe #102 can help.

**Comment by Berkmann18** [comment]
@blackxored Does this still happen?

**Comment by Berkmann18** [comment]
@blackxored Friendly ping.

**Comment by blackxored** [comment]
7.x or so I believe (current) doesn’t have this issue, sorry for the late response.

**Comment by Berkmann18** [comment]
Okay, good to hear.
