### ISSUE TITLE
Saving a repo host URL different than "github.com" results in error when next attempting to add a new contributor

### ISSUE THREAD

**Issue by lpatmo** [all-contributors/all-contributors-cli#87]
all-contributors-cli version: ^4.11.1
node version: 9.4.0
npm (or yarn) version: 5.6.0

Steps I took:

1) 
```
$ npx all-contributors init
? What's the name of the repository? codebuddies
? Who is the owner of the repository? codebuddies
? What is the repository type? GitHub
? Where is the repository hosted? https://github.com/codebuddiesdotorg/codebuddies
? In which file should contributors be listed? README.md
? Do you want a badge tallying the number of contributors? Yes
? In which file should the badge be shown? README.md
? How big should the avatars be? (in px) 100
? Do you want this badge to auto-commit when contributors are added? Yes
```
2)
```
$ npm run contributors:add --lpatmo code

> codebuddies@1.0.0 contributors:add /Users/lindapeng/Desktop/lindaprojects/codebuddies
> all-contributors add "code"

? What are the contribution types? 💻  Code
Not Found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codebuddies@1.0.0 contributors:add: `all-contributors add "code"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codebuddies@1.0.0 contributors:add script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lindapeng/.npm/_logs/2018-03-19T21_13_45_845Z-debug.log
```

However, when I hit "enter" for the `Where is the repository hosted?` question and then try adding a contributor, I'm able to add a contributor successfully:

```
$ npx all-contributors init
? What's the name of the repository? codebuddies
? Who is the owner of the repository? codebuddies
? What is the repository type? GitHub
? Where is the repository hosted? https://github.com
? In which file should contributors be listed? README.md
? Do you want a badge tallying the number of contributors? Yes
? In which file should the badge be shown? README.md
? How big should the avatars be? (in px) 100
? Do you want this badge to auto-commit when contributors are added? Yes

$ npm run contributors:add --lpatmo code

> codebuddies@1.0.0 contributors:add /Users/lindapeng/Desktop/lindaprojects/codebuddies
> all-contributors add "code"

? What are the contribution types? 💻  Code
```

I tried pasting in https://github.com/jfmengels/all-contributors-cli as the value for the `Where is the repository hosted?` question, and got the same error when I tried adding a new contributor too.

**Comment by kentcdodds** [comment]
Yes, we should probably change that question to be a list of options rather than a free form field. Would you like to [make a pull request](http://makeapullrequest.com) to make that happen?

**Comment by lpatmo** [comment]
Ah, so it's not meant to store the value of the Github repository, but to store values like `Github` or `Bitbucket`?

**Comment by kentcdodds** [comment]
Yeah, it's supposed to be `github` or `gitlab`. Those are the supported hosts currently I believe.

**Comment by lpatmo** [comment]
A meta question: do we need the "Where is the repository hosted" question still, if the "What is the repository type?" question is asking the same thing, and supports a choice of either GitHub or GitLab?

**Comment by kentcdodds** [comment]
Honestly, I've kinda lost control of this project a bit and I don't quite know the answer to your question. I have very limited time to maintain this project. Maybe one of the other maintainers can answer.

**Comment by machour** [comment]
Hi @lpatmo,

GitLab can be installed on your own server begin a custom URL, this is why we need that information. 

I'll gladly merge a PR to make this clearer!

**Comment by lpatmo** [comment]
Thanks @machour and @kentcdodds!

@machour: Can you clarify what option(s) need to be the choices under `"Where is the repository hosted"`?

**Comment by machour** [comment]
This shouldn't be a select/choice item, but a manual input, as it is now.

Currently, if you select GitLab or GitHub in the previous question, the "Where is the repository hosted" is automatically filled:

<img width="517" alt="screen shot 2018-03-21 at 10 26 02 am" src="https://user-images.githubusercontent.com/304450/37702304-60b85b82-2cf2-11e8-9a69-9411c406a284.png">

The PR should just changed the wording of "Where is the repository hosted?" to something clearer to the user:

> Where is the repository hosted? (hit Enter if it's on github.com)

or maybe change the process like so:

> What is the repository type ? GitLab
> Is your repository hosted on gitlab.com? (yes/no)

Then, if no is selected:

> Where is your repository hosted (https://yourserver.com/): 

this time, without defaulting to https://gitlab.com/

**Comment by speenzor** [comment]
Thank you for posting this. I also had this problem and was able to fix it by just hitting enter on the default answer. I'll create the PR to make it clearer.

**Comment by Berkmann18** [comment]
@spencercorwin How's the PR going?

**Comment by spencercorwin** [comment]
My PR was accepted Jul 16, 2018. It's PR #103 
https://github.com/all-contributors/all-contributors-cli/pull/103

**Comment by Berkmann18** [comment]
Okay, in this case, this issue is resolved.
